---
- name: oracle bpm qs 12c (12.2.1)
  hosts: 127.0.0.1

  roles:
    - role: oracle-soa
      oracle_soa_version: 12c
      oracle_soa_release: 12.2.1
      oracle_soa_quick_installation: yes
      oracle_soa_install_bpm: yes

      oracle_bpm_qs_installers_12_2_1_1of2: roles/oracle-soa/files/fmw_12.2.1.0.0_bpmqs_Disk1_1of2.zip
      oracle_bpm_qs_installers_12_2_1_2of2: roles/oracle-soa/files/fmw_12.2.1.0.0_bpmqs_Disk1_2of2.zip
