# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  config.vm.synced_folder "/home/jeqo/oracle/fmw/installers/", "/srv/files"

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test02" do |test02|
    test02.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test03" do |test03|
    test03.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test04" do |test04|
    test04.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test05" do |test05|
    test05.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test06" do |test06|
    test06.vm.box = "jeqo/oracle-jdk-8-centos7"
  end
end
