# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  config.vm.synced_folder "/home/jeqo/oracle/fmw/installers/", "/srv/files"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.define "test01" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test02" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test03" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test04" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test05" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test06" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test07" do |node|
    node.vm.box = "syscomiddleware/oracle-weblogic-11g-centos7"
  end
end
